Script started on 廿十七年三月十三日 (週一) 廿二時45分38秒
]0;williamchen@williamchen-Aspire-VN7-591G: ~/lab1[01;32mwilliamchen@williamchen-Aspire-VN7-591G[00m:[01;34m~/lab1[00m$ g++ -o lab1 lab1.cpp
]0;williamchen@williamchen-Aspire-VN7-591G: ~/lab1[01;32mwilliamchen@williamchen-Aspire-VN7-591G[00m:[01;34m~/lab1[00m$ ./lab1
98
98 49 148 74 37 112 56 28 14 7 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;williamchen@williamchen-Aspire-VN7-591G: ~/lab1[01;32mwilliamchen@williamchen-Aspire-VN7-591G[00m:[01;34m~/lab1[00m$ exit

Script done on 廿十七年三月十三日 (週一) 廿二時46分卅一秒
